### ISSUE TITLE
Really would love to see this working with fitbit-0.3.0 ..

### ISSUE THREAD

**Issue by moseisleydk** [edrabbit/fitbitsplunk#1]
Really would love to see this working with fitbit-0.3.0 .. and FitbitOauth2Client

I get:

AttributeError: 'FitbitOauth2Client' object has no attribute 'fetch_request_token'

Also sorry to see You site http://www.geeked.info/ is stale, lots of good (but old) stuff

**Comment by edrabbit** [comment]
Sorry for the lack of updates! I no longer have a fitbit, but hopefully someone feels motivated enough to fork or submit a pull request!

**Comment by moseisleydk** [comment]
Thanks for the reply anyway, apriciated !
